controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

joint_broad:
  ros__parameters: {}

diff_cont:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.35
    wheel_radius: 0.05

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    publish_rate: 50.0

    cmd_vel_timeout: 0.25
    use_stamped_vel: false
